apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: shopfast
spec:
  serviceName: db-service
  replicas: 1
  selector:
    matchLabels:
      app: shopfast-db
  template:
    metadata:
      labels:
        app: shopfast-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
          name: postgres
        envFrom:
        - secretRef:
            name: db-secrets
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - admin
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - admin
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-script
        configMap:
          name: db-init-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
  namespace: shopfast
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS products (
        id SERIAL PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        price DECIMAL(10, 2) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    INSERT INTO products (name, price) VALUES
        ('Laptop Pro 15"', 1299.99),
        ('Wireless Mouse', 29.99),
        ('Mechanical Keyboard', 89.99),
        ('4K Monitor', 449.99),
        ('USB-C Hub', 49.99)
    ON CONFLICT DO NOTHING;
